// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDiX3OOeXsG9kgRQLYn5eMaJDO45S6wrg',
    appId: '1:875575292371:web:9149a2b0a8893e5108bf26',
    messagingSenderId: '875575292371',
    projectId: 'workout-app-b66dd',
    authDomain: 'workout-app-b66dd.firebaseapp.com',
    storageBucket: 'workout-app-b66dd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNrqWfwuDBiu3Xglwg1L0QYUrzjD-U0Uw',
    appId: '1:875575292371:android:be4a07af7f47118208bf26',
    messagingSenderId: '875575292371',
    projectId: 'workout-app-b66dd',
    storageBucket: 'workout-app-b66dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7eCjO9yTjIDcuP6Mb94rhh1HgGwYL8aI',
    appId: '1:875575292371:ios:c7e3f5571b2f21b408bf26',
    messagingSenderId: '875575292371',
    projectId: 'workout-app-b66dd',
    storageBucket: 'workout-app-b66dd.appspot.com',
    iosBundleId: 'com.example.workoutTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7eCjO9yTjIDcuP6Mb94rhh1HgGwYL8aI',
    appId: '1:875575292371:ios:c7e3f5571b2f21b408bf26',
    messagingSenderId: '875575292371',
    projectId: 'workout-app-b66dd',
    storageBucket: 'workout-app-b66dd.appspot.com',
    iosBundleId: 'com.example.workoutTracker',
  );
}
